name = "core-github-api"
main = "src/index.ts"
compatibility_date = "2023-07-01"

[observability]
enabled = true

[vars]
LOG_LEVEL = "info"

# [secrets]
# GITHUB_TOKEN

[[kv_namespaces]]
binding = "ETAG_KV"
id = "eed6ba4656704616acf168be80ba770a"
preview_id = "cfc441ebd1d8492497f49e88ae98aa2f"
