name = "cloudflare-worker-github-proxy"
main = "src/index.ts"
compatibility_date = "2023-07-01"

[vars]
LOG_LEVEL = "info"

# [secrets]
# GITHUB_TOKEN

[[kv_namespaces]]
binding = "ETAG_KV"
id = "dummy_id_for_local_dev"
preview_id = "dummy_id_for_local_dev"
