name = "core-github-api"
main = "src/index.ts"
compatibility_date = "2023-07-01"

[observability]
enabled = true

[vars]
LOG_LEVEL = "info"

# [secrets]
# GITHUB_TOKEN
# WORKER_API_KEY

[[kv_namespaces]]
binding = "ETAG_KV"
id = "eed6ba4656704616acf168be80ba770a"
preview_id = "cfc441ebd1d8492497f49e88ae98aa2f"

[[d1_databases]]
binding = "CORE_GITHUB_API"
database_name = "core-github-api"
database_id = "8d945e71-1c5b-499a-a0b8-71baf2353fdd"
preview_database_id = "797f10ce-b971-469a-bee3-0f09f7d0e7a6"
migrations_dir = "migrations"
